spring:
  datasource:
    url: jdbc:mysql://localhost:3306/personal_log_db?characterEncoding=UTF-8
    username: root
    password: 12345678

#    druid连接池配置相关
    druid:
#     初始大小
      initial-size: 5
      min-idle: 5
      max-active: 20
#     超时时间
      max-wait: 60000
#     配置建哥多久才进行一次检测，检测需要关闭的空闲链接，单位毫秒
      time-between-eviction-runs-millis: 60000
#     链接在连接池中最小生存时间 单位/ms
      min-evictable-idle-time-millis: 300000
