package com.personal.blog.dao;

import com.personal.blog.entity.ArticleMessage;
import com.personal.blog.entity.ArticleMessageExample;
import java.util.List;

public interface ArticleMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_message
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_message
     *
     * @mbg.generated
     */
    int insert(ArticleMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_message
     *
     * @mbg.generated
     */
    int insertSelective(ArticleMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_message
     *
     * @mbg.generated
     */
    List<ArticleMessage> selectByExample(ArticleMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_message
     *
     * @mbg.generated
     */
    ArticleMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ArticleMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ArticleMessage record);
}