package com.personal.blog.dao;

import com.personal.blog.entity.ArticleComment;
import com.personal.blog.entity.ArticleCommentExample;
import java.util.List;

public interface ArticleCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_comment
     *
     * @mbg.generated
     */
    int insert(ArticleComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_comment
     *
     * @mbg.generated
     */
    int insertSelective(ArticleComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_comment
     *
     * @mbg.generated
     */
    List<ArticleComment> selectByExample(ArticleCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_comment
     *
     * @mbg.generated
     */
    ArticleComment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ArticleComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ArticleComment record);
}