package com.personal.blog.dao;

import com.personal.blog.entity.ArticleCategory;
import com.personal.blog.entity.ArticleCategoryExample;
import java.util.List;

public interface ArticleCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_category
     *
     * @mbg.generated
     */
    int insert(ArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_category
     *
     * @mbg.generated
     */
    int insertSelective(ArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_category
     *
     * @mbg.generated
     */
    List<ArticleCategory> selectByExample(ArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_category
     *
     * @mbg.generated
     */
    ArticleCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ArticleCategory record);
}