package com.personal.blog.dao;

import com.personal.blog.entity.ArticleSort;
import com.personal.blog.entity.ArticleSortExample;
import java.util.List;

public interface ArticleSortMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_sort
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_sort
     *
     * @mbg.generated
     */
    int insert(ArticleSort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_sort
     *
     * @mbg.generated
     */
    int insertSelective(ArticleSort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_sort
     *
     * @mbg.generated
     */
    List<ArticleSort> selectByExample(ArticleSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_sort
     *
     * @mbg.generated
     */
    ArticleSort selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_sort
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ArticleSort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_sort
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ArticleSort record);
}