package com.personal.blog.dao;

import com.personal.blog.entity.ArticleContent;
import com.personal.blog.entity.ArticleContentExample;
import java.util.List;

public interface ArticleContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_content
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_content
     *
     * @mbg.generated
     */
    int insert(ArticleContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_content
     *
     * @mbg.generated
     */
    int insertSelective(ArticleContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_content
     *
     * @mbg.generated
     */
    List<ArticleContent> selectByExampleWithBLOBs(ArticleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_content
     *
     * @mbg.generated
     */
    List<ArticleContent> selectByExample(ArticleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_content
     *
     * @mbg.generated
     */
    ArticleContent selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_content
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ArticleContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_content
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ArticleContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_content
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ArticleContent record);
}