package com.personal.blog.dao;

import com.personal.blog.entity.CategoryInfo;
import com.personal.blog.entity.CategoryInfoExample;
import java.util.List;

public interface CategoryInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_info
     *
     * @mbg.generated
     */
    int insert(CategoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_info
     *
     * @mbg.generated
     */
    int insertSelective(CategoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_info
     *
     * @mbg.generated
     */
    List<CategoryInfo> selectByExample(CategoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_info
     *
     * @mbg.generated
     */
    CategoryInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CategoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_category_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CategoryInfo record);
}