package com.personal.blog.dao;

import com.personal.blog.entity.SortInfo;
import com.personal.blog.entity.SortInfoExample;
import java.util.List;

public interface SortInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sort_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sort_info
     *
     * @mbg.generated
     */
    int insert(SortInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sort_info
     *
     * @mbg.generated
     */
    int insertSelective(SortInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sort_info
     *
     * @mbg.generated
     */
    List<SortInfo> selectByExample(SortInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sort_info
     *
     * @mbg.generated
     */
    SortInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sort_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SortInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sort_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SortInfo record);
}