package com.personal.blog.entity;

import java.util.Date;

public class ArticleCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_article_category.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_article_category.category_id
     *
     * @mbg.generated
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_article_category.article_id
     *
     * @mbg.generated
     */
    private Long articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_article_category.create_by
     *
     * @mbg.generated
     */
    private Date createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_article_category.modified_by
     *
     * @mbg.generated
     */
    private Date modifiedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_article_category.id
     *
     * @return the value of tbl_article_category.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_article_category.id
     *
     * @param id the value for tbl_article_category.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_article_category.category_id
     *
     * @return the value of tbl_article_category.category_id
     *
     * @mbg.generated
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_article_category.category_id
     *
     * @param categoryId the value for tbl_article_category.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_article_category.article_id
     *
     * @return the value of tbl_article_category.article_id
     *
     * @mbg.generated
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_article_category.article_id
     *
     * @param articleId the value for tbl_article_category.article_id
     *
     * @mbg.generated
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_article_category.create_by
     *
     * @return the value of tbl_article_category.create_by
     *
     * @mbg.generated
     */
    public Date getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_article_category.create_by
     *
     * @param createBy the value for tbl_article_category.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(Date createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_article_category.modified_by
     *
     * @return the value of tbl_article_category.modified_by
     *
     * @mbg.generated
     */
    public Date getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_article_category.modified_by
     *
     * @param modifiedBy the value for tbl_article_category.modified_by
     *
     * @mbg.generated
     */
    public void setModifiedBy(Date modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
}