package com.personal.blog.entity;

import java.util.Date;

public class SortInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sort_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sort_info.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sort_info.number
     *
     * @mbg.generated
     */
    private Byte number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sort_info.create_by
     *
     * @mbg.generated
     */
    private Date createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sort_info.modified_by
     *
     * @mbg.generated
     */
    private Date modifiedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sort_info.is_effective
     *
     * @mbg.generated
     */
    private Boolean isEffective;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sort_info.id
     *
     * @return the value of tbl_sort_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sort_info.id
     *
     * @param id the value for tbl_sort_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sort_info.name
     *
     * @return the value of tbl_sort_info.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sort_info.name
     *
     * @param name the value for tbl_sort_info.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sort_info.number
     *
     * @return the value of tbl_sort_info.number
     *
     * @mbg.generated
     */
    public Byte getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sort_info.number
     *
     * @param number the value for tbl_sort_info.number
     *
     * @mbg.generated
     */
    public void setNumber(Byte number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sort_info.create_by
     *
     * @return the value of tbl_sort_info.create_by
     *
     * @mbg.generated
     */
    public Date getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sort_info.create_by
     *
     * @param createBy the value for tbl_sort_info.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(Date createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sort_info.modified_by
     *
     * @return the value of tbl_sort_info.modified_by
     *
     * @mbg.generated
     */
    public Date getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sort_info.modified_by
     *
     * @param modifiedBy the value for tbl_sort_info.modified_by
     *
     * @mbg.generated
     */
    public void setModifiedBy(Date modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sort_info.is_effective
     *
     * @return the value of tbl_sort_info.is_effective
     *
     * @mbg.generated
     */
    public Boolean getIsEffective() {
        return isEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sort_info.is_effective
     *
     * @param isEffective the value for tbl_sort_info.is_effective
     *
     * @mbg.generated
     */
    public void setIsEffective(Boolean isEffective) {
        this.isEffective = isEffective;
    }
}